apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-pd
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4