apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-mysql-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /test
    server: 10.250.217.218