apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-mysql-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
